config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :tags, only: [:index, :show]
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/list', to: 'static_pages#list'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
    acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :detect_device
  protect_from_forgery with: :exception

  private
    def detect_device
      case request.user_agent
        #when /iPad/
        #    request.variant = :mobile
        when /iPod/
            request.variant = :mobile
        when /iPhone/
            request.variant = :mobile
        when /Android/
            request.variant = :mobile
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def about
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :tag_list)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @lists = Post.page(params[:page]).reverse_order
  end

  def about
  end

  def list
    @lists = Post.page(params[:page]).reverse_order
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name , tag_path(tag) %>

app/views/layouts/_footer.html+mobile.erb
<footer class="footer">
  <small>
    created by Ryosuke Fujii
  </small>
</footer>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    created by Ryosuke Fujii
  </small>
  <nav>
    <ul>
      <% if current_user %>
        <li><%= link_to('sign_out', destroy_user_session_path, :method => :delete) %></li>
        <li><%= link_to('change password', edit_registration_path(:user)) %></li>
        <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html+mobile.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"data-toggle="collapse"data-target="#navbarEexample8">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          MY BLOG
        </a>
      </div>

      <div class="collapse navbar-collapse" id="navbarEexample8">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home" , root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Post", list_path %></li>
        <li><%= link_to "Tag", tags_path %></li>
      </ul>
    </div>
  </div>
</div>
</nav>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home" , root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Post", list_path %></li>
        <li><%= link_to "Tag", tags_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html+mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYBLOG</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('/favicon.ico') %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div class="img"><%= image_tag("Myblog_logosp.png") %></div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MYBLOG</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('/favicon.ico') %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>
  <body>
    <%= image_tag("MYBLOG-logo.png", :class => "img") %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.cktext_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
 <h2><%= link_to post.title, post_path(post) %></h2>

app/views/posts/index.html.erb
<%# output:title,time,tag,description,picture %>

<% @posts.each do |post| %>
  <br><h1><%= post.title %></h1><br>
  <br><%= post.created_at.to_s(:ymd) %><br> 
      <%= render post.tags %><br>
  <h1><%= post.description %><br></h1>
    <br>
    <p><img alt="" src="/uploads/ckpost/pictures/6/content_line_8.png" style="width: 800px; height: 134px;" /></p>
<% end %>

<%# output:pagination %>
<%= paginate @posts %>

app/views/posts/show.html.erb
<%#<p id="notice"><%= notice ></p> %>
<div class="post">
  <h1><div class="heading1"><%= @post.title %></div></h1>
  <div class="time">
    <%= @post.created_at.to_s(:ja) %>
  </div>
  <div class="tags">
    <% @post.tags.each do |tag| %>
      <span class="square_btn"><%= render tag %></span>
    <% end %>
  </div>
  <div class="description">
    <%== @post.description %>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="about">ABOUT ME</div>
<p>会津大学コンピュータ理工学部４年の藤井 亮輔です。</p>
<p>まずはじめに私は、2016年夏に精神的な病気になり休学をしました。そして、治療を行い病気を治すことができました。</p>
<p>治療開始から約半年後に回復をしスーパーのアルバイトを始めました。朝と昼は自宅でプログラミング、夜はアルバイトという生活を送りました。</p>
<p>日々アルバイトをする中、昼間はPHPで掲示板を作成しました。</p>
<p>掲示板を完成し、次にフレームワークを用いてWebアプリを作成したいと思い、チュートリアルが充実していて日本語の情報が多くとっつきやすいと感じたRubyonRailsのチュートリアルをやりました。チュートリアルをやっている途中で自分でなにかを作ってみたい！と思い、このブログを作ってみました。</p>
<p>そして、2018年4月より復学をし今に至ります。</p>


<p></p>
<p></p>
<p></p>
<p>言語:　C、C++、Java、PHP、Ruby</p>
<p>好き:　アニメ、ゲーム</p>
<p>興味:　Go、Vue.js、機械学習</p>


<p></p>
<p></p>
<p></p>
<p></p>

app/views/static_pages/home.html.erb
<%# output:title,time,tag,description,picture(line) %>
<% @lists.each do |list| %>
  <div class="post">
    <h1><div class="heading1"><%= list.title %></div></h1>
    <div class="time">
      <%= list.created_at.to_s(:ja) %>
    </div>
    <br />
    <div class="tags">
      <% list.tags.each do |tag| %>
      <span class="square_btn"><%= render tag %></span>
    <% end %>
    </div>
    <div class="description">
      <%== list.description %>
    </div>
  </div>
<% end %>
<%# output:pagination %>
<%= paginate @lists %>

app/views/static_pages/list.html.erb
<div class="list">
  <h1>Post</h1>
  <%= render @lists %>
</div>
<%= paginate(@lists) %>

app/views/tags/index.html.erb
<div class="tag">
  <h1>Tag</h1>
  <p><%= render @tags %></p>
</div>

app/views/tags/show.html.erb
<div class="tagshow"><%= @tag.name %>
  <ul>
    <%= render @posts %>
  </ul>
</div>